### ISSUE TITLE
Build instructions? 

### ISSUE THREAD

**Issue by zbeekman** [pvigier/gitamine#2]
I too am interested in trying this on macOS (See #1). However, I am happy to build it myself, but have limited experience with typescript & electron.

To build it do I just use the typical npm workflow?

**Comment by pvigier** [comment]
Hi,

Yes, normally you just have to run these commands to install and launch the app:

```
npm install
npm start
```

You may need to install a C/C++ build toolchain to build native dependencies if you have not already one installed.

Best,
Pierre

**Comment by zbeekman** [comment]
Awesome, thanks!
